CREATE TABLE IF NOT EXISTS role (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO role  (name) VALUES('ROLE_ADMIN'),("ROLE_USER"), ("ROLE_MAGASINIER"), ("ROLE_OBSERVEUR"), ("ROLE_DRIVER");