CREATE TABLE IF NOT EXISTS role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);


INSERT IGNORE INTO role (name)
VALUES ('ROLE_ADMIN'), ('ROLE_USER'), ('ROLE_MAGASINIER'), ('ROLE_OBSERVEUR'), ('ROLE_DRIVER');
